Develop a TODO app
robinbenitezmora/to-do-react-app pull request #1
Opened 2022-09-12 21:16 UTC by robinbenitezmora

Following with the React topic we are building an application that is able to add, remove and read data about personal daily tasks.

2022-09-13 16:00 UTC, carlosmuerto requested changes
# Request Changes
Good job! this looks promising. there is some change I wanna address.

## general comments
- [ ] please don't disable Linters at the file level, Linters are important for code readability.
- [ ] Please Address in the PR description a resume of what kind of change are you implementing.
- [ ] you are using git-flow, but your beach name doesn't follow the conversion `feature/<added-feature-name>` in this case could be `feature/todo`

### please check in-line comments for more in-depth details.

2022-09-13 16:00 UTC, carlosmuerto commented on README.md
check this description in your README.

2022-09-13 16:00 UTC, carlosmuerto commented on README.md
> +- [Live Demo Link](https://github.com/robinbenitezmora/to-do-react-app)
If you going to implement gh-pages, don't forget fix this link

2022-09-13 16:00 UTC, carlosmuerto commented on src/index.js
> +);
This form of Init the rendering is deprecated use what comes default in the create-react-app instead.
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot 
```

2022-09-13 16:00 UTC, carlosmuerto commented on src/reportWebVitals.js
>        getCLS(onPerfEntry);
This Component looks like it's not used, please remove it if not used.

2022-09-13 16:00 UTC, carlosmuerto commented on src/App.js
> +/*eslint-disable*/
This Component looks like it's not used, please remove it if not used.

2022-09-16 14:54 UTC, robinbenitezmora commented on README.md
Thanks for helping Carlos. I have done some changes, especially correcting linters errors, however, functionality is not over. Please check my changes and give me your opinion.

2022-09-16 20:14 UTC, carlosmuerto approved these changes
Hi @robinbenitezmora , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

 - [Part 1 - React tutorial: The beginner's guide to learning React in 2020](https://ibaslogic.com/react-tutorial-for-beginners/). ✅ 
 - [Part 2 - Working with React form and handling event](https://ibaslogic.com/react-form-handling/). ✅ 
- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅

2022-09-16 21:26 UTC, merged